# Generated by Django 4.0.3 on 2022-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('poll', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('family', models.CharField(max_length=255, null=True)),
                ('post_card', models.IntegerField(null=True)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
    ]
