# Generated by Django 4.0.3 on 2022-05-24 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='family',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
