# Generated by Django 4.0.3 on 2022-05-24 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_add_family_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='post_card',
            field=models.IntegerField(default=111111111),
            preserve_default=False,
        ),
    ]
