# Generated by Django 4.0.3 on 2022-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='family',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='post_card',
            field=models.IntegerField(null=True),
        ),
    ]
